name: Run Node Daily

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs daily at 00:00 UTC
  workflow_dispatch:      # Optional: run manually

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Node file
        run: node index.js